version: '3.8'

services:
  # NestJS application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: mysql://username:password@db:3306/dbname
    networks:
      - nest
    restart: on-failure
    # command: npx prisma db push --schema=./prisma/schema.prisma

  # MySQL database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - nest

networks:
  nest:
